- ang/civicase.ang.php
- ang/civicase/DashboardCtrl.html
- ang/civicase/DashboardCtrl.js
- ang/crmRouteBinder.js
- ang/crmRouteBinder.md
- ang/uibTabsetClass.ang.php
- ang/uibTabsetClass.js
- ang/uibTabsetClass.md
Requires: https://github.com/civicrm/civicrm-core/pull/10545
> CRM-20756 - Dashboard - Add skeletal screen `/case`

- ang/civicase/CaseList.js
- civicase.php
This depends on https://github.com/civicrm/civicrm-core/pull/10573
> CRM-20776 - "Cases" menu should point to Angular UI's

- ang/civicase/CaseViewHeader.html
> HW-345: Fix peoples tab markup

- ang/civicase/ViewPeople.html
- css/caseList.css
- css/caseView.css
**Before**
**After**
**Shoreditch PR:** [#29](https://github.com/civicrm/org.civicrm.shoreditch/pull/29)
**Note:**
- Discussed with Alessandro to add all civicase changes on civicase repo and only genric chnages should go on Shoreditch repo.
- Confirmed with Jon about "Tag buttons", "Radio buttons" and "Check box". It should styled same as invision design.
> HW-345: Fix peoples tab page design

- ang/civicase/FileFilter.html
- ang/civicase/FileList.html
- ang/civicase/Filesize.js
- ang/civicase/Uploader.html
- ang/civicase/ViewPeople.html
- css/activityFeed.css
- css/caseList.css
- css/caseView.css
- css/uploader.css
> HW-346: Files tab page design

- ang/civicase/CaseList.html
- css/activityFeed.css
- css/caseList.css
- css/caseView.css
> HW-355: Fix case table view page design

- ang/civicase/CaseViewOtherCases.html
- ang/civicase/CaseViewSummary.html
- ang/civicase/View.js
- css/caseView.css
> HW-370: Fixed other cases section

- css/caseList.css
> HW-355: Fixed checkbox alignment

- ang/civicase/Search.html
- css/general.css
> HW-356: Changed layout of case search page

- ang/civicase/ActivityControls.html
- ang/civicase/ActivityFilters.html
- ang/civicase/FileFilter.html
- css/activityFeed.css
**Before:**
**After:**
**Note:**
This resolves only Point 1 of Ticket: Feed filters & config (top part of a feed that allows you to add/remove filters and change display settings)
> HW-366: Fixed activity feed control and filters

- ang/civicase/CaseViewHeader.html
- css/caseView.css
> HW-371:Fixed case detail view header

- ang/civicase/CaseList.html
- ang/civicase/CaseList.js
- ang/civicase/ViewPeople.html
- ang/civicase/ViewPeople.js
- css/caseView.css
> HW-345:Fixed peoples tab markup and styling

- ang/civicase/ActivityFilters.js
- css/activityFeed.css
- css/activityView.css
**Before:**
- No fixed activity pane
**After:**
**Note:**
This PR contains minor changes for activity filter to match sticky fits
> HW-375:Styled indenpendent vertical scroll for activity pane

- css/activityView.css
**Note:** 
Minor fix to make scroll visible only when needed
> HW-375: Fixed scrollbar for activity pane

- ang/civicase/DashboardSummary.html
- css/dashboard.css
> HW-378: Styling Case pipelines dashlet

- ang/civicase/ActivityFilters.js
- css/activityFeed.css
**After:**
Note:
- This PR fixed changes related to z-index and dynamic height.
- vertical align to top for filters
> HW-374: Styling sticky filters on feed

- ang/civicase/CaseList.html
- css/caseList.css
- css/general.css
> HW-384: Fixed activity card wrap and border issues

- ang/civicase/CaseList.html
- ang/civicase/CaseList.js
- css/caseList.css
**Before:**
**After:**
**Note:**
This PR also makes header sticky for table which can not be seen by screenshot.
> HW-385: Styled table view sticky headings

- css/caseView.css
> HW-345: Fixed pager styling

- ang/civicase/ActivityCard.html
- ang/civicase/ActivityFeed.js
- ang/civicase/ActivityListItem.html
- ang/civicase/CaseListTable.html
- ang/civicase/DashboardCtrl.js
- ang/civicase/Utils.js
This depends on https://github.com/civicrm/civicrm-core/pull/10979
> Add case info to activities on dashboard

- ang/civicase/CaseTabs.html
- ang/civicase/CaseViewHeader.html
- css/activityFeed.css
- css/caseList.css
- css/caseView.css
- css/general.css
> HW-346: Fix issues related to buttons and radius

- css/activityFeed.css
> HW-374: Fix z-index issue

- ang/crmRouteBinder.js
(Note that I had did a couple other changes as part of this -- 8de2660e2 and 9886af18c -- but I pushed those directly to master because they seemed more straightforward.)
I believe this implements the second approach discussed in #39 -- it avoids propagating mere defaults to the URL bar. To see this in action, you might:
* Navigate to `civicrm/case/a/#/case/list`. Observe the URL stays the same
* Click on a case. Observe the URL changes to something like `civicrm/case/a/#/case/list?caseId=15`.
* Click on the "Files" tab. Observe the URL changes to something like `civicrm/case/a/#/case/list?caseId=15&focus=1&tab=files`
* Click on the "People" tab. Observe the URL changes to something like `civicrm/case/a/#/case/list?caseId=15&focus=1&tab=people`.
* Press the back button. It returns to the …
>  crmRouteBinder - When using a default, don't put it in the URL (#39)

- ang/civicase/DashboardSummary.html
- css/dashboard.css
> HW-378:Fixed case pipelines dashlet as per mockup

- css/activityFeed.css
> HW-374: Fixed broken z-index on popups

- ang/civicase/ActivityItemInner-communication.html
- ang/civicase/ActivityItemInner-default.html
- ang/civicase/CaseList.js
- ang/civicase/Search.js
- css/caseList.css
- css/general.css
> HW-355: Fixed activity and fixed header issues

- ang/civicase/ActivityCardMenu.html
- ang/civicase/ActivityItemMenu.html
- css/activityFeed.css
- css/general.css
After:
Styling new parts of activity feed with some fixes
> HW-366: Styling activity feeds

- css/caseView.css
This PR styles colors and margin/padding of buttons and text  to match UI.
> HW-371: Styling margins and colors

- ang/civicase/ActivityFilters.js
- ang/civicase/ActivityList.html
- ang/civicase/ActivityListItem.html
- ang/civicase/ActivityView.html
- css/activityFeed.css
- css/activityView.css
Fixing new button and styling for sticky section as per new changes.
**Additional:**
It fixes hover and viewing effect for list item of activity feed.
> HW-375: Fixed sticky header issue and styled new buttons

- css/activityFeed.css
This PR styles button for edit option for any draft activity.
> HW-375: Styling edit draft button

- ang/civicase/CaseList.js
- ang/civicase/DashboardCtrl.html
- css/caseList.css
- css/dashboard.css
This PR styles recent cases dashlet on case dashboard
> HW-391:Styling recent cases dashlet

- css/activityFeed.css
This PR adds padding and repairs background color for .cb-dot
> HW-366:Styled padding and background issue

- ang/civicase/ActivityItemInner-communication.html
- ang/civicase/ActivityItemInner-default.html
- ang/civicase/ActivityListItem.html
- ang/civicase/CaseViewHeader.html
- css/caseView.css
Description:
This PR styles/fixes minor snagging around civicase to make it look better.
**Fixture screenshot:**
**Note:** 
Indentation removal of span is intentional to prevent browser from adding ending space in the tags.
> HW-402: Styled and fixed elements around civicase

- css/caseView.css
This PR is to fix collapsible content inline editing with different container.
> HW-373: Fixed broken CSS of shoreditch

- css/dashboard.css
> HW-378: Fixed dynamic height calculation

- css/activityFeed.css
- css/caseView.css
- css/general.css
**Before:**
**After:**
**Note:**
@colemanw This also resolves https://github.com/civicrm/org.civicrm.civicase/blob/e46a2e95cced3ae1e4fc4c28b05136aa7a1dc46a/css/caseView.css#L338
> HW-403: Styled activity feeds and it's spacing

- ang/civicase/ViewPeople.html
- css/caseList.css
- css/caseView.css
- css/general.css
> HW-345: Styled People tab changes

- css/activityFeed.css
> HW-375: Added border to table bottom

- css/activityFeed.css
- css/caseView.css
- css/general.css
- css/uploader.css
Description:
This PR fixes minor css patches for multiple tickets
> HW-371/HW-382: Fixing minor patches

- ang/civicase/CaseViewOtherCases.html
- ang/civicase/DashboardCtrl.html
- css/caseList.css
- css/caseView.css
- css/dashboard.css
**Before**
**After**
This PR contains multiple style changes as per UI guidelines
> Multiple Style Changes

- ang/civicase/CaseViewSummary.html
- css/caseView.css
> HW 373: Added subject lable

- css/activityFeed.css
- css/uploader.css
> HW-346: Fixed file tab issues

- css/activityFeed.css
**Before:**
**After:**
Jumping is non-visible
> HW-374: Fixed sticky filter jumping

- ang/civicase/CaseViewCommunicationRecent.html
- ang/civicase/CaseViewTasks.html
- ang/civicase/DashboardCtrl.html
- css/caseView.css
- css/dashboard.css
- css/general.css
> HW-406: Styled empty dahslet placeholders

- ang/civicase/CaseViewSummary.html
- css/caseView.css
- css/general.css
> HW-341: Styling UI snaggin on summary page

- css/activityFeed.css
- css/dashboard.css
**Before:**
**After:**
**Before:**
**After:**
> HW-391/HW-346: Fixed css issues

- css/activityFeed.css
> HW-405: Fixed z-index issue

- ang/civicase/ActivityFilters.js
- ang/civicase/DashboardCtrl.html
- css/activityFeed.css
- css/caseList.css
- css/caseView.css
- css/dashboard.css
- css/uploader.css
_This PR fixes below issues,_
1. Tabs of dashboard to look same as navigation of activity pane.
2. Make dashboard background color and padding changes to make it look more near mockup
3. Jump/Snagging of filters on activity and dashboard activity tabs
4. Remove Jumping of page when viewing case activity with only 1/2 activities in the list
5. Fix placeholders
6. Remove extra CSS classes of checkboxes/radio from styling
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
@guanhuan 
This covers our blocker points from below,
> HW-411: Styled dashboard to near mockup

- ang/civicase/CaseList.js
- ang/civicase/CaseListTable.html
- ang/civicase/CaseViewPlaceholder.html
- ang/civicase/View.js
- css/activityFeed.css
- css/caseView.css
- css/general.css
This PR 
- Adds skeleton placeholders to caselist table on dashboard and manage case page
- Removes unwanted border from activity card of case list
**Before:**
**After:**
**Before:**
**After:**
@guanhuan 
This covers below points from blockers
> Styled skeleton for case list on dashboard and manage cases

- ang/civicase/CaseListTable.html
- css/activityFeed.css
- css/caseList.css
- css/caseView.css
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Note:**
Other points of Tickets are already resolved with different blockers and no need to work on that again. It is tested though.
> HW-405: Fixed overflow and snagging issues

- css/dashboard.css
> HW-411: Fixed button radius and padding

- ang/civicase/ActivityFilters.js
- ang/civicase/CaseTabs.html
- ang/civicase/View.js
- css/activityView.css
- css/caseView.css
**Before:**
**After:**
**Note:**
@colemanw This is my first directive in Angular, Let me know if something is going wrong in this.
> HW-414: Styled Tabset and related calculation for sticky scroll

- ang/civicase/ActivityFilters.js
- ang/civicase/DashboardCtrl.html
- ang/civicase/DashboardCtrl.js
- css/activityFeed.css
- css/dashboard.css
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Note:**
actual change in `ang/civicase/DashboardCtrl.html` contains only below change
1. `<div class="dashboard-tab-container clearfix">` added on line 6
2. line 7 for `cleafix` class and `uib-tabset-affix` directive
**Important:** This a temporary solution, code will be moved to global affix directive once built
> HW-415: Styled Dashboard activity tab

- css/activityFeed.css
> HW-417: Fixed page jumps on activity feed

- css/caseView.css
> HW-341: Styled custom fields on case detail page

- css/caseList.css
> HW-411: Fixed stacked sticky elements

- ang/civicase.ang.php
- ang/civicase/Actions.js
This depends on https://github.com/civicrm/civicrm-core/pull/11223
> Add print/merge document action

- ang/civicase/DashboardCtrl.html
- css/dashboard.css
> HW-421: Styled dashboard case statistics/breakdown

- css/caseList.css
This PR fixes issues related to animation glitches of td tags in chrome browser.
**Before:**
**After:**
> HW-437: Fixed scrolling element transforms

- css/activityFeed.css
- css/caseList.css
- css/caseView.css
- css/dashboard.css
**Before: Sticky tabs - dashboard **
**After:**
**Before: Missing menu**
**After:**
**Before: odd sticky table header **
**After:**
> HW-453: Fixed sticky sections based on shoreditch new changes

- api/v3/Case/Getstats.php
- api/v3/Case/Gettypestats.php
https://github.com/civicrm/org.civicrm.civicase/issues/113
> CiviCase dashboard includes deleted case count

- api/v3/Case/Getstats.php
- api/v3/Case/Gettypestats.php
> Filter out disabled case types from stats

- info.xml
> Fix release date of new version

- info.xml
Doesn't seem like this is what we are doing these days since there are other options @colemanw can we remove requirement?
> Remove shoreditch requirement

- CRM/Civicase/Upgrader/Base.php
- civicase.civix.php
> Regenerate Civix files
